USE [master]
GO

CREATE DATABASE [msdb]
    CONTAINMENT = NONE
    ON PRIMARY
    (
        NAME = N'MSDBData',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\MSDBData.mdf',
        SIZE = 19008 KB,
        MAXSIZE = Unlimited,
        FILEGROWTH = 10%
    )
    LOG ON
    (
        NAME = N'MSDBLog',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\MSDBLog.ldf',
        SIZE = 18240 KB,
        MAXSIZE = 2147483648 KB,
        FILEGROWTH = 10%
    )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
   EXEC [msdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [msdb] SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [msdb] SET ANSI_NULLS OFF
ALTER DATABASE [msdb] SET ANSI_PADDING OFF
ALTER DATABASE [msdb] SET ANSI_WARNINGS OFF
ALTER DATABASE [msdb] SET ARITHABORT OFF
ALTER DATABASE [msdb] SET AUTO_CLOSE OFF
ALTER DATABASE [msdb] SET AUTO_SHRINK OFF
ALTER DATABASE [msdb] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [msdb] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [msdb] SET CURSOR_DEFAULT GLOBAL
ALTER DATABASE [msdb] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [msdb] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [msdb] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [msdb] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [msdb] SET ENABLE_BROKER
ALTER DATABASE [msdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [msdb] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [msdb] SET TRUSTWORTHY ON
ALTER DATABASE [msdb] SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE [msdb] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [msdb] SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE [msdb] SET HONOR_BROKER_PRIORITY OFF
ALTER DATABASE [msdb] SET RECOVERY SIMPLE
ALTER DATABASE [msdb] SET MULTI_USER
ALTER DATABASE [msdb] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [msdb] SET DB_CHAINING ON
ALTER DATABASE [msdb] SET FILESTRAM (NON_TRANSACTED_ACCESS = OFF)
ALTER DATABASE [msdb] SET TARGET_RECOVERY_TIME = 60 SECONDS
ALTER DATABASE [msdb] SET DELAYED_DURABILITY = DISABLED
ALTER DATABASE [msdb] SET QUERY_STORE = OFF
ALTER DATABASE [msdb] SET READ_WRITE
GO

CREATE USER [##MS_PolicyEventProcessingLogin##] FOR LOGIN [##MS_PolicyEventProcessingLogin##] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [##MS_PolicyTsqlExecutionLogin##] FOR LOGIN [##MS_PolicyTsqlExecutionLogin##] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [dbo] FOR LOGIN [sa] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [guest] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[guest] -- SQL_USER
CREATE USER [INFORMATION_SCHEMA] -- SQL_USER
CREATE USER [MS_DataCollectorInternalUser] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [sys] -- SQL_USER
GO
