USE [master]
GO

CREATE DATABASE [master]
    CONTAINMENT = NONE
    ON PRIMARY
    (
        NAME = N'master',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\master.mdf',
        SIZE = 6080 KB,
        MAXSIZE = Unlimited,
        FILEGROWTH = 10%
    )
    LOG ON
    (
        NAME = N'mastlog',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\mastlog.ldf',
        SIZE = 2048 KB,
        MAXSIZE = Unlimited,
        FILEGROWTH = 10%
    )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
   EXEC [master].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [master] SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [master] SET ANSI_NULLS OFF
ALTER DATABASE [master] SET ANSI_PADDING OFF
ALTER DATABASE [master] SET ANSI_WARNINGS OFF
ALTER DATABASE [master] SET ARITHABORT OFF
ALTER DATABASE [master] SET AUTO_CLOSE OFF
ALTER DATABASE [master] SET AUTO_SHRINK OFF
ALTER DATABASE [master] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [master] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [master] SET CURSOR_DEFAULT GLOBAL
ALTER DATABASE [master] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [master] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [master] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [master] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [master] SET DISABLE_BROKER
ALTER DATABASE [master] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [master] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [master] SET TRUSTWORTHY OFF
ALTER DATABASE [master] SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE [master] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [master] SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE [master] SET HONOR_BROKER_PRIORITY OFF
ALTER DATABASE [master] SET RECOVERY SIMPLE
ALTER DATABASE [master] SET MULTI_USER
ALTER DATABASE [master] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [master] SET DB_CHAINING ON
ALTER DATABASE [master] SET FILESTRAM (NON_TRANSACTED_ACCESS = OFF)
ALTER DATABASE [master] SET TARGET_RECOVERY_TIME = 0 SECONDS
ALTER DATABASE [master] SET DELAYED_DURABILITY = DISABLED
ALTER DATABASE [master] SET QUERY_STORE = OFF
ALTER DATABASE [master] SET READ_WRITE
GO

CREATE USER [##MS_PolicyEventProcessingLogin##] FOR LOGIN [##MS_PolicyEventProcessingLogin##] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [dbo] FOR LOGIN [sa] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [guest] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[guest] -- SQL_USER
CREATE USER [INFORMATION_SCHEMA] -- SQL_USER
CREATE USER [sys] -- SQL_USER
GO
