USE [master]
GO

CREATE DATABASE [AdventureWorks2022]
    CONTAINMENT = NONE
    ON PRIMARY
    (
        NAME = N'AdventureWorks2022',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\AdventureWorks2022.mdf',
        SIZE = 204800 KB,
        MAXSIZE = Unlimited,
        FILEGROWTH = 65536 KB
    )
    LOG ON
    (
        NAME = N'AdventureWorks2022_log',
        FILENAME = N'D:\SQLServer\MSSQL16.TYPHOON\MSSQL\DATA\AdventureWorks2022_log.ldf',
        SIZE = 73728 KB,
        MAXSIZE = 2147483648 KB,
        FILEGROWTH = 65536 KB
    )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
   EXEC [AdventureWorks2022].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorks2022] SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [AdventureWorks2022] SET ANSI_NULLS ON
ALTER DATABASE [AdventureWorks2022] SET ANSI_PADDING ON
ALTER DATABASE [AdventureWorks2022] SET ANSI_WARNINGS ON
ALTER DATABASE [AdventureWorks2022] SET ARITHABORT ON
ALTER DATABASE [AdventureWorks2022] SET AUTO_CLOSE OFF
ALTER DATABASE [AdventureWorks2022] SET AUTO_SHRINK OFF
ALTER DATABASE [AdventureWorks2022] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [AdventureWorks2022] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [AdventureWorks2022] SET CURSOR_DEFAULT GLOBAL
ALTER DATABASE [AdventureWorks2022] SET CONCAT_NULL_YIELDS_NULL ON
ALTER DATABASE [AdventureWorks2022] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [AdventureWorks2022] SET QUOTED_IDENTIFIER ON
ALTER DATABASE [AdventureWorks2022] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [AdventureWorks2022] SET DISABLE_BROKER
ALTER DATABASE [AdventureWorks2022] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [AdventureWorks2022] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [AdventureWorks2022] SET TRUSTWORTHY OFF
ALTER DATABASE [AdventureWorks2022] SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE [AdventureWorks2022] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [AdventureWorks2022] SET READ_COMMITTED_SNAPSHOT ON
ALTER DATABASE [AdventureWorks2022] SET HONOR_BROKER_PRIORITY OFF
ALTER DATABASE [AdventureWorks2022] SET RECOVERY SIMPLE
ALTER DATABASE [AdventureWorks2022] SET MULTI_USER
ALTER DATABASE [AdventureWorks2022] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [AdventureWorks2022] SET DB_CHAINING OFF
ALTER DATABASE [AdventureWorks2022] SET FILESTRAM (NON_TRANSACTED_ACCESS = OFF)
ALTER DATABASE [AdventureWorks2022] SET TARGET_RECOVERY_TIME = 0 SECONDS
ALTER DATABASE [AdventureWorks2022] SET DELAYED_DURABILITY = DISABLED
ALTER DATABASE [AdventureWorks2022] SET QUERY_STORE = OFF
ALTER DATABASE [AdventureWorks2022] SET READ_WRITE
GO

CREATE USER [dbo] FOR LOGIN [sa] WITH DEFAULT_SCHEMA=[dbo] -- SQL_USER
CREATE USER [guest] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[guest] -- SQL_USER
CREATE USER [INFORMATION_SCHEMA] -- SQL_USER
CREATE USER [sys] -- SQL_USER
GO
